image: pythondiscord/snekbox-ci:latest

variables:
  DOCKER_DRIVER: overlay

#services:
#  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - pipenv sync --dev
    - pipenv run lint
    - pipenv run test
    - pipenv run buildbox
    - pipenv run pushbox
