image: pythondiscord/snekbox-base:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
  - build

build:
  stage: build
  script:
    - chmod +x scripts/ci.sh
    - bash scripts/ci.sh
    - pipenv run lint
    - pipenv run test
