image: pythondiscord/snekbox-ci:latest

variables:
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/pipenv-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pipenv-cache"
    - "$CI_PROJECT_DIR/.venv"

services:
  - docker:dind

stages:
  - build

build:
  tags:
    - docker
    - pythondiscord
  stage: build
  script:
    - pipenv install --dev --deploy
    - pipenv run lint
    - pipenv run test
