image: pythondiscord/snekbox-base:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
  - build

build:
  stage: build
  script:
    - ls -lah
    - pipenv run lint
    - pipenv run test
