image: pythondiscord/snekbox-ci:latest

variables:
  DOCKER_DRIVER: overlay
  RMQ_HOST: rabbit

services:
  - docker:dind
  - name: rabbitmq:3.7.5-alpine
    alias: rabbit


stages:
  - build

build:
  stage: build
  script:
    - docker ps
    - pipenv sync --dev
    - pipenv run lint
    - pipenv run test
    - pipenv run buildbox
    - pipenv run pushbox
