repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
      args: [--config=.flake8]
      exclude: ^tests/
      additional_dependencies: [
        flake8-docstrings,
        flake8-bugbear,
        flake8-import-order,
        flake8-tidy-imports,
        flake8-todo,
        flake8-string-format,
        flake8-formatter-junit-xml,
        flake8-quotes
      ]

