language: python
python:
  - "3.6"

branches:
  only:
    - "master"

dist: xenial
sudo: required

#services:
#  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libprotobuf-dev libstdc++6

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_NOSPIN=1
    - PIPENV_HIDE_EMOJIS=1

install:
  - pip install pipenv
  - pipenv sync --dev --three
script:
  - chmod +x scripts/ci.sh
  - bash scripts/ci.sh
  - pipenv run lint
  - pipenv run test
#after_success:
#  - bash scripts/deploy.sh

cache: pip

notifications:
  email: false
