language: python
python:
  - "3.6"

branches:
  only:
    - "master"

dist: xenial
sudo: required

services:
  - rabbitmq
  #- docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libprotobuf-dev libstdc++6

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_NOSPIN=1
    - PIPENV_HIDE_EMOJIS=1
    - RABBITMQ_HOST=localhost

install:
  - sudo pip install pipenv
  - sudo pipenv sync --dev --three
script:
  - sudo chmod +x scripts/ci.sh
  - sudo bash scripts/ci.sh
  - sudo pipenv run lint
  - sudo pipenv run test
#after_success:
#  - bash scripts/deploy.sh

cache: pip

notifications:
  email: false
