# https://aka.ms/yaml

jobs:
- job: test
  displayName: 'Lint'

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Set Python version'
    inputs:
      versionSpec: '3.7.x'
      addToPath: true

  - script: pip3 install pipenv
    displayName: 'Install pipenv'

  - script: pipenv install --dev --deploy --system
    displayName: 'Install project using pipenv'

  - script: python3 -m flake8 --format junit-xml --output-file test-lint.xml
    displayName: 'Run linter'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Snekbox Flake8 Lint Results'

- job: build
  displayName: 'Build'
  dependsOn: test
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  steps:
  - task: Docker@1
    displayName: 'Login: Docker Hub'

    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerHub'
      command: 'login'

  - script: |
      if [[ -n "$(git diff HEAD~ -- docker/base.Dockerfile)" ]]; then
        echo "##vso[task.setvariable variable=BASE_CHANGED]1"
      fi

      if [[ -n "$(git diff HEAD~ -- Pipfile* docker/venv.Dockerfile)" ]]; then
        echo "##vso[task.setvariable variable=VENV_CHANGED]1"
      fi
    displayName: 'Check Changed Files'

  - script: docker build -t pythondiscord/snekbox-base:latest -f docker/base.Dockerfile .
    displayName: 'Build Base Image'
    condition: and(succeeded(), variables.BASE_CHANGED)

  - script: docker build -t pythondiscord/snekbox-venv:latest -f docker/venv.Dockerfile .
    displayName: 'Build Virtual Environment Image'
    condition: and(succeeded(), or(variables.BASE_CHANGED, variables.VENV_CHANGED))

  - script: docker build -t pythondiscord/snekbox:latest -f docker/Dockerfile .
    displayName: 'Build Final Image'

  - script: docker push pythondiscord/snekbox-base:latest
    displayName: 'Push Base Image to Dockerhub'
    condition: and(succeeded(), variables.BASE_CHANGED)

  - script: docker push pythondiscord/snekbox-venv:latest
    displayName: 'Push Virtual Environment Image to Dockerhub'
    condition: and(succeeded(), or(variables.BASE_CHANGED, variables.VENV_CHANGED))

  - script: docker push pythondiscord/snekbox:latest
    displayName: 'Push Final Image to Dockerhub'
