# https://aka.ms/yaml

jobs:
- job: test
  displayName: 'Lint'

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Set Python version'
    inputs:
      versionSpec: '3.7.x'
      addToPath: true

  - script: pip3 install pipenv
    displayName: 'Install pipenv'

  - script: pipenv install --dev --deploy --system
    displayName: 'Install project using pipenv'

  - script: python3 -m flake8 --format junit-xml --output-file test-lint.xml
    displayName: 'Run linter'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Snekbox Flake8 Lint Results'

- job: build
  displayName: 'Build'
  dependsOn: test

  steps:
  - task: Docker@1
    displayName: 'Login: Docker Hub'

    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerHub'
      command: 'login'

  - script: |
      REQUEST_URL="https://dev.azure.com/python-discord/${SYSTEM_TEAMPROJECTID}/_apis/build/builds?queryOrder=finishTimeDescending&resultFilter=succeeded&\$top=1&repositoryType=${BUILD_REPOSITORY_PROVIDER}&repositoryId=${BUILD_REPOSITORY_NAME}&branchName=${SYSTEM_PULLREQUEST_TARGETBRANCH:-BUILD_SOURCEBRANCH}&api-version=5.0"
      echo "Retrieving previous build's commit using $REQUEST_URL"

      PREV_COMMIT="$(curl -sSL "${REQUEST_URL}" | grep -Po '"sourceVersion":"\K.*?[^\\](?=",)')"
      echo "Retrieved $PREV_COMMIT as previous build's commit."

      if [[ -z $PREV_COMMIT ]] || [[ -n "$(git diff $PREV_COMMIT -- docker/base.Dockerfile)" ]]; then
        echo "Detected changes in docker/base.Dockerfile"
        echo "##vso[task.setvariable variable=BASE_CHANGED]1"
      fi

      if [[ -z $PREV_COMMIT ]] || [[ -n "$(git diff $PREV_COMMIT -- Pipfile* docker/venv.Dockerfile)" ]]; then
        echo "Detected changes in Pipfile, Pipfile.lock, and/or docker/venv.Dockerfile"
        echo "##vso[task.setvariable variable=VENV_CHANGED]1"
      fi
    displayName: 'Check Changed Files'

  - script: docker build -t pythondiscord/snekbox-base:latest -f docker/base.Dockerfile .
    displayName: 'Build Base Image'
    condition: and(succeeded(), variables.BASE_CHANGED)

  - script: docker build -t pythondiscord/snekbox-venv:latest -f docker/venv.Dockerfile .
    displayName: 'Build Virtual Environment Image'
    condition: and(succeeded(), or(variables.BASE_CHANGED, variables.VENV_CHANGED))

  - script: docker build -t pythondiscord/snekbox:latest -f docker/Dockerfile .
    displayName: 'Build Final Image'

  - script: echo "Base image push simulation"
    displayName: 'Push Base Image to Dockerhub'
    condition: and(succeeded(), variables.BASE_CHANGED)

  - script: echo "Venv image push simulation"
    displayName: 'Push Virtual Environment Image to Dockerhub'
    condition: and(succeeded(), or(variables.BASE_CHANGED, variables.VENV_CHANGED))

  - script: echo "Final image push simulation"
    displayName: 'Push Final Image to Dockerhub'
