# https://aka.ms/yaml

jobs:
- job: test
  displayName: 'Lint & Test'

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - script: docker build -t pythondiscord/snekbox-base:latest -f docker/base.Dockerfile .
      displayName: 'Build Base Image'

    - script: |
        id="$(docker images -q --no-trunc pythondiscord/snekbox-base:latest)"
        if [[ -z "${id}" ]]; then
          (>&2 echo 'failed to get ID of pythondiscord/snekbox-base:latest')
            exit 1
        fi

        printf '%s' "${id}" >> base.sha256
      displayName: 'Create Digest Artifact'

    - task: PublishPipelineArtifact@2
      inputs:
        path: base.sha256
        artifact: base_id
