version: '3'
services:
  pdrmq:
    hostname: "pdrmq"
    image: rabbitmq:3.7.5-alpine
    networks:
      - sneknet

  pdsnekbox:
    hostname: "pdsnekbox"
    image: pythondiscord/snekbox:latest
    networks:
      - sneknet
    environment:
      RMQ_HOST: pdrmq

  pdsnekboxweb:
    hostname: "pdsnekboxweb"
    image: pythondiscord/snekboxweb:latest
    networks:
      - sneknet
    ports:
       - "5000:5000"
    expose:
      - "5000"
    environment:
      RMQ_HOST: pdrmq


networks:
  sneknet:
